src/com/warriorsofthenorth/domain/Category.java
package com.warriorsofthenorth.domain;

/**
 * Created by Florian Mitterbauer on 2/3/15.
 */
public class Category {

    private String category;

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }
}

src/com/warriorsofthenorth/domain/Expense.java
package com.warriorsofthenorth.domain;

import java.util.Date;

/**
 * Created by Florian Mitterbauer on 2/3/15.
 */
public class Expense {
    private String description;
    private Category category;
    private double amount;
    private Date date;

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
}

web/WEB-INF/classes/com/warriorsofthenorth/domain/Category.java
package com.warriorsofthenorth.domain;

/**
 * Created by Florian Mitterbauer on 2/3/15.
 */
public class Category {

    private String category;

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }
}

web/WEB-INF/classes/com/warriorsofthenorth/domain/Expense.java
package com.warriorsofthenorth.domain;

import java.util.Date;

/**
 * Created by Florian Mitterbauer on 2/3/15.
 */
public class Expense {
    private String description;
    private Category category;
    private double amount;
    private Date date;

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
}

src/com/warriorsofthenorth/web/ExpenseBean.java
package com.warriorsofthenorth.web;

import com.warriorsofthenorth.domain.Category;
import com.warriorsofthenorth.domain.Expense;
import com.warriorsofthenorth.service.ExpenseService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.model.SelectItem;
import java.util.*;

/**
 * Created by Florian Mitterbauer on 2/8/15.
 */

@ManagedBean(name="expenseBean", eager=true)
@SessionScoped
public class ExpenseBean {

    @ManagedProperty(value="#{expenseService}")
    private ExpenseService expenseService;

    private String description;
    private String category;
    private double amount;


    public List<Expense> getExpenses(){

        return this.expenseService.readAllExpenses();
    }

    public void setExpense(){
        Expense expense = new Expense();
        expense.setDescription(this.description);
        Category mycategory = new Category();
        mycategory.setCategory(category);
        expense.setCategory(mycategory);
        expense.setDate(new Date());
        expense.setAmount(this.amount);
        this.expenseService.addExpense(expense);
    }


    private ArrayList<SelectItem> categories = null;


    public List<String> getCategoriesList(){
        List<String> categoryNameList = new LinkedList<String>();
        for(Category categoryLoop : this.expenseService.readAllCategories()){
            categoryNameList.add(categoryLoop.getCategory());
        }
        return categoryNameList;
    }

    public ArrayList<SelectItem> getCategories(){
        categories = new ArrayList<SelectItem>();
        categories.add(new SelectItem(null,"Select a Category"));
        for(Category categoryLoop : this.expenseService.readAllCategories()){
            categories.add(new SelectItem(categoryLoop.getCategory(),categoryLoop.getCategory()));
        }
        return categories;
    }


    public void addCategory(){
        Category mycategory = new Category();
        mycategory.setCategory(category);
        this.expenseService.addCategory(mycategory);
    }

    public void deleteCategory(){
        Category mycategory = new Category();
        mycategory.setCategory(category);
        this.expenseService.deleteCategory(mycategory);
    }


    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }


    public ExpenseService getExpenseService() {
        return expenseService;
    }

    public void setExpenseService(ExpenseService expenseService) {
        this.expenseService = expenseService;
    }
}

web/WEB-INF/classes/com/warriorsofthenorth/web/ExpenseBean.java
package com.warriorsofthenorth.web;

import com.warriorsofthenorth.domain.Category;
import com.warriorsofthenorth.domain.Expense;
import com.warriorsofthenorth.service.ExpenseService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.model.SelectItem;
import java.util.*;

/**
 * Created by Florian Mitterbauer on 2/8/15.
 */

@ManagedBean(name="expenseBean", eager=true)
@SessionScoped
public class ExpenseBean {

    @ManagedProperty(value="#{expenseService}")
    private ExpenseService expenseService;

    private String description;
    private String category;
    private double amount;


    public List<Expense> getExpenses(){

        return this.expenseService.readAllExpenses();
    }

    public void setExpense(){
        Expense expense = new Expense();
        expense.setDescription(this.description);
        Category mycategory = new Category();
        mycategory.setCategory(category);
        expense.setCategory(mycategory);
        expense.setDate(new Date());
        expense.setAmount(this.amount);
        this.expenseService.addExpense(expense);
    }


    private ArrayList<SelectItem> categories = null;


    public List<String> getCategoriesList(){
        List<String> categoryNameList = new LinkedList<String>();
        for(Category categoryLoop : this.expenseService.readAllCategories()){
            categoryNameList.add(categoryLoop.getCategory());
        }
        return categoryNameList;
    }

    public ArrayList<SelectItem> getCategories(){
        categories = new ArrayList<SelectItem>();
        categories.add(new SelectItem(null,"Select a Category"));
        for(Category categoryLoop : this.expenseService.readAllCategories()){
            categories.add(new SelectItem(categoryLoop.getCategory(),categoryLoop.getCategory()));
        }
        return categories;
    }


    public void addCategory(){
        Category mycategory = new Category();
        mycategory.setCategory(category);
        this.expenseService.addCategory(mycategory);
    }

    public void deleteCategory(){
        Category mycategory = new Category();
        mycategory.setCategory(category);
        this.expenseService.deleteCategory(mycategory);
    }


    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }


    public ExpenseService getExpenseService() {
        return expenseService;
    }

    public void setExpenseService(ExpenseService expenseService) {
        this.expenseService = expenseService;
    }
}

web/addcategory.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
<head>
    <title>Expenses-Manager</title>
    <link rel="stylesheet" type="text/css" href="css/expensestyle.css"/>

</head>
<body>
<div id="menu">
    <ul>
        <li><a href="addexpense.xhtml">New Expense</a></li>
        <li><a href="listexpenses.xhtml">List Expenses</a></li>
        <li><a href="addcategory.xhtml">New Category</a></li>
        <li><a href="deletecategory.xhtml">Delete Category</a></li>
        <li><a href="viewcategories.xhtml">View Categories</a></li>
    </ul>
</div>
<div id="content">
<h:form>
    <h3>Add new Category:</h3>
    <hr/>
    <table>
        <tr>
            <td>Category Name :</td>
            <td><h:inputText id="categoryInput" size="25" value="#{expenseBean.category}"
                             validator="#{duplicateCategoryValidator.validate}">
                <f:validateLength minimum="1" maximum="25"/>
                <f:validator binding="#{duplicateCategoryValidator}"/>
            </h:inputText></td>
            <td><h:message for="categoryInput" style="color:red"/></td>
        </tr>
        <tr>
            <td> </td>
            <td><h:commandButton value="Add Category"
                                 action="#{expenseBean.addCategory}" /></td>
        </tr>
    </table>
</h:form>
</div>
</body>
</html>

web/addexpense.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
<head>
    <title>Expenses-Manager</title>
    <link rel="stylesheet" type="text/css" href="css/expensestyle.css"/>

</head>
<body>
<div id="menu">
    <ul>
        <li><a href="addexpense.xhtml">New Expense</a></li>
        <li><a href="listexpenses.xhtml">List Expenses</a></li>
        <li><a href="addcategory.xhtml">New Category</a></li>
        <li><a href="deletecategory.xhtml">Delete Category</a></li>
        <li><a href="viewcategories.xhtml">View Categories</a></li>
    </ul>
</div>
<div id="content">
<h:form>
    <h3>Add new Expense:</h3>
    <hr/>
    <table>
        <tr>
            <td>Description :</td>
            <td><h:inputText id="descriptionInput" size="50" value="#{expenseBean.description}">
                <f:validateLength minimum="1" maximum="50"/>
            </h:inputText></td>
            <td><h:message for="descriptionInput" style="color:red"/></td>
        </tr>
        <tr>
            <td>Description :</td>
            <td><h:selectOneMenu id="categoryDropDown" value="#{expenseBean.category}" required="true"
                                 requiredMessage="Please select a Category for Deletion.">
                <f:selectItems value="#{expenseBean.categories}" />
            </h:selectOneMenu></td>
            <td><h:message for="categoryDropDown" style="color:red"/></td>
        </tr>
        <tr>
            <td>Amount(Euro) :</td>
            <td><h:inputText id="amountInput" size="25" value="#{expenseBean.amount}">
                <f:convertNumber minFractionDigits="2"/>
            </h:inputText></td>
            <td><h:message for="amountInput" style="color:red"/></td>
        </tr>
        <tr>
            <td> </td>
            <td><h:commandButton value="Add Expense"
                                 action="#{expenseBean.setExpense}" /></td>
        </tr>
    </table>
</h:form>
</div>
</body>
</html>

web/deletecategory.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
<head>
    <title>Expenses-Manager</title>
    <link rel="stylesheet" type="text/css" href="css/expensestyle.css"/>
</head>
<body>
<div id="menu">
    <ul>
        <li><a href="addexpense.xhtml">New Expense</a></li>
        <li><a href="listexpenses.xhtml">List Expenses</a></li>
        <li><a href="addcategory.xhtml">New Category</a></li>
        <li><a href="deletecategory.xhtml">Delete Category</a></li>
        <li><a href="viewcategories.xhtml">View Categories</a></li>

    </ul>
</div>
<div id="content">
    <h3>Delete Category: </h3>
    <hr/>
    <h:form>
        <h:selectOneMenu id="categoryList" value="#{expenseBean.category}" required="true"
                     requiredMessage="Please select a Category for Deletion.">
             <f:selectItems value="#{expenseBean.categories}" />
        </h:selectOneMenu>
        <h:message for="categoryList" style="color:red"/>

        <h:commandButton value="Delete Category" action="#{expenseBean.deleteCategory}" />
    </h:form>
    <p></p>
    <p></p>
</div>


</body>
</html>

web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
<h:head>
    <link rel="stylesheet" type="text/css" href="css/expensestyle.css"/>
</h:head>
<h:body>
    <div id="menu">
    <ul>
        <li><a href="addexpense.xhtml">New Expense</a></li>
        <li><a href="listexpenses.xhtml">List Expenses</a></li>
        <li><a href="addcategory.xhtml">New Category</a></li>
        <li><a href="deletecategory.xhtml">Delete Category</a></li>
        <li><a href="viewcategories.xhtml">View Categories</a></li>

    </ul>
    </div>
<div id="content">
    <h3>Welcome to the Expense-Manager</h3>
    <hr/>
    My Expense-Manager is realized with the JSF Framework (2.0) and MySQL as<br/>
    data Storage. <p/>
    Code and Design by Florian Mitterbauer
</div>
    <p/>
</h:body>
</html>

web/listexpenses.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
<head>
    <title>Expenses-Manager</title>
    <link rel="stylesheet" type="text/css" href="css/expensestyle.css"/>
</head>
<body>
<div id="menu">
    <ul>
        <li><a href="addexpense.xhtml">New Expense</a></li>
        <li><a href="listexpenses.xhtml">List Expenses</a></li>
        <li><a href="addcategory.xhtml">New Category</a></li>
        <li><a href="deletecategory.xhtml">Delete Category</a></li>
        <li><a href="viewcategories.xhtml">View Categories</a></li>

    </ul>
</div>

<div id="content">
<h3>All Expenses:</h3>
    <hr/>
<h:dataTable value="#{expenseBean.expenses}" var="c" id="expensetable">
    <h:column><f:facet name="header">Description</f:facet>
        #{c.description}
    </h:column>
    <h:column><f:facet name="header">Category</f:facet>
        #{c.category.category}
    </h:column>
    <h:column><f:facet name="header">Amount</f:facet>
        #{c.amount}
    </h:column>
    <h:column><f:facet name="header">Date</f:facet>
        #{c.date}
    </h:column>
</h:dataTable>
</div>

</body>
</html>

web/viewcategories.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
<head>
    <title>Expenses-Manager</title>
    <link rel="stylesheet" type="text/css" href="css/expensestyle.css"/>
</head>
<body>
<div id="menu">
    <ul>
        <li><a href="addexpense.xhtml">New Expense</a></li>
        <li><a href="listexpenses.xhtml">List Expenses</a></li>
        <li><a href="addcategory.xhtml">New Category</a></li>
        <li><a href="deletecategory.xhtml">Delete Category</a></li>
        <li><a href="viewcategories.xhtml">View Categories</a></li>
    </ul>
</div>
<div id="content">
    <h3>Categories: </h3>
    <hr/>
    <h:dataTable value="#{expenseBean.categoriesList}" var="c" id="expensetable">
        <h:column><f:facet name="header">Category</f:facet>
            #{c}
        </h:column>
    </h:dataTable>

</div>


</body>
</html>